### ISSUE TITLE
T_05_Create Employee Profile Page

### ISSUE THREAD

**Issue by costaivo** [costaivo/MEAN-EmployeeReview#55]
Allow editing of following fields

- First Name
- Middle Name
- Last Name
- Designation [junior programmer, programmer, Senior programmer, etc]
- Date of Joining
- *Birth day
- Team Name
- Skills (free text form)

**Comment by nudayabhanu-cci** [comment]
Created Employee profile page which updates new data inserted by user into MongoDB
(adds data to existing collection after user has successfully logged in)
